#!/bin/bash
#SBATCH -A TG-CCR140008 # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J helloworld
#SBATCH -o helloworld.stdout
#SBATCH -N 16 -n 16
#SBATCH -p normal
#SBATCH -t 00:01:00
./helloworld